package com.KotHub.models

data class KHIssue(val id: Int?,
                   val url: String?,
                   val repositoryUrl: String?,
                   val labelsUrl: String?,
                   val commentsUrl: String?,
                   val eventsUrl: String?,
                   val htmlUrl: String?,
                   val number: Int?,
                   val state: String?,
                   val title: String?,
                   val user: KHUser?,
                   val labels: KHLabel?,
                   val assignee: KHUser?,
                   val assignees: List<KHUser>?,
                   val milestone: KHMilestone?,
                   val locked: Boolean?,
                   val comments: Int?,
                   val pullRequests: KHPullRequests?,
                   val closedAt: String?,
                   val createdAt: String?,
                   val updatedAt: String?,
                   val repository: KHRepository?)
